image: debian:jessie

# Is performed before the scripts in the stages step
before_script:  
  - source /etc/profile

# Defines stages which are to be executed
stages:  
  - build

# Stage "build"
run-build:  
  stage: build
  script:
    - echo "deb http://deb.debian.org/debian/ jessie main" > /etc/apt/sources.list
    - echo "deb http://security.debian.org/ jessie/updates main" >> /etc/apt/sources.list
    - echo "deb http://deb.debian.org/debian/ jessie-backports main" >> /etc/apt/sources.list
    - apt-get update
    - apt-get install -y git dh-make build-essential autoconf autotools-dev
    - apt-get install -y liburcu-dev libunwind-dev libev-dev libsocket6-perl ragel libio-socket-inet6-perl libmaxminddb-dev
    - autoreconf -vif
    - cp COPYING debian/copyright
    - dpkg-buildpackage -i -us -uc -b
    - mkdir build
    - mv ../*.deb build/

  # This stage is only executed for new tags
  #only:
  #  - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*