image: debian:jessie

variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_SUBMODULE_STRATEGY: normal
  CONTAINER_IMAGE: "geodns/gdnsd/image:latest"

# Is performed before the scripts in the stages step
before_script:  
  - source /etc/profile

# Defines stages which are to be executed
stages:  
  - build-package
  - build

# Stage "build"
build-package:  
  stage: build-package
  script:
    - echo "deb http://deb.debian.org/debian/ jessie main" > /etc/apt/sources.list
    - echo "deb http://security.debian.org/ jessie/updates main" >> /etc/apt/sources.list
    - echo "deb http://deb.debian.org/debian/ jessie-backports main" >> /etc/apt/sources.list
    - apt-get update
    - apt-get install -y git dh-make build-essential autoconf autotools-dev libtool dh-autoreconf dh-systemd libwww-perl libhttp-daemon-perl
    - apt-get install -y liburcu-dev libunwind-dev libev-dev libsocket6-perl ragel libio-socket-inet6-perl libmaxminddb-dev 
    - autoreconf -vif
    - cp COPYING debian/copyright
    - dpkg-buildpackage -i -us -uc -b
    - mkdir build
    - mv ../*.deb build/
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

build-image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CONTAINER_IMAGE .
    - docker push $CI_REGISTRY/$CONTAINER_IMAGE
  dependencies:
    - build-deb
